export enum ENUM_ERROR_CODE {
  INVALID_CREDS = 'ERR_INVALID_CREDS',
  INVALID_DATA = 'ERR_INVALID_DATA',
  ENTITY_NOT_FOUND = 'ERR_ENTITY_NOT_FOUND',
  BAD_REQUEST = 'ERR_BAD_REQUEST',
  INTERNAL = 'ERR_INTERNAL',
  FORBIDDEN = "ERR_FORBIDDEN",
  CONFLICT = "ERR_CONFLICT"
}

export enum ENUM_USER_ROLE {
  STUDENT = 1,
  ADMIN = 2,
}

export enum ENUM_PROGRAMME_STATUS {
  ALL = 0, // Means all status
  ACTIVE = 1,
  COMPLETED = 2,
  FINISHED = 3,
  DROPPED = 4,
}

export enum ENUM_DAY {
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
  SUNDAY = 7,
}

export enum ENUM_CLASS_TYPE {
  LECTURE = 1,
  PRACTICAL = 2,
  TUTORIAL = 3,
  WORKSHOP = 4,
}

export enum ENUM_PROGRAMME_INTAKE_STATUS {
  INACTIVE = 0,
  ACTIVE = 1,
}

export enum ENUM_STUDY_MODE {
  FULL_TIME = 1,
  PART_TIME = 2
}
